language: node_js
node_js:
  - 6.11.1
  - 6.11.2
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: gXOZ5Pwq/MNBHVOyp2QeLqiiGEo87MHN+ikwNdNPKv/Z3dbS07eBWDBawlTgC9ErmcrMrn3nOSbjj9WrJnqI14wI/vPy3yK3Nn+nfPRwaEuAQ/ZpuW+pOs+CTTCdYI3aYwQUBA0fug8hrBK/yf55StZZo7+oC/yZog8HZtEXsnsndusMbp+Nqbm5nVzGXRao3Himd8kXYgPrrcAv7nX6PgEJSu3Qq/+7kjDuIqKggnoqRgBq3tAO1SPZfhkNI3QBtrGjB3QC7CbM5vIRlmrxyoqNsjgvICqPVhH7+nxTCzhIPSRy7U0Do0GpUDN8VqK6lKy1I7cNlfshZWOL7qxr7hz4RXjYRouN07ci4Na+PonBXhd37KeMm7xicm5XEHkqzYGZAxpXzV7lbG+WIqINi7lGlnFvcc6/vkaVBNfJrHps0ucKZ2dmmShmuF4vcHT6Sg1LmcOeLaKK+GyKLcd/Z3Tr9rMXpuqqQssdbpbNPCUUT/5y3SBTkk2VJL78jdy6TBO+1SsG9F75OEWxSUEvkhhkO2iXyrvNdoHGzVRBEMI0jctSGWMLCg+cJOYz7wgU0qq+VV/pjtdssz7lP+Ds9AM7hQmZ0q3eB4ZChxm8hccwY1YUoFTWrei/EVChwaPlN+c2wubMV++H+ELAMZ4m52G3ptpLfYoy3eMz1YUIrGI=
  on:
    tags: true
    repo: yoctore/yocto-hint
before_install: npm install -g grunt-cli
install: npm install
