language: node_js
node_js:
- 8.11.4
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install: npm install -g grunt-cli
install: npm install
jobs:
  include:
  - stage: deploy
    node_js: 8.11.4
    deploy:
      provider: npm
      email: technique@yocto.re
      api_key:
        secure: SBuvAuHkFmkiHinJJqf3IpJzJviwiWEmNGC6VbGvHWP1FI/fMzNemb5ighQyyKWIjvzkkJWpl7IvZ5VTREFW0pcL9/PNQ0kJyWxUIp+agHXvryZhzyJbDVRE3p74/1vXa9q9flObgjP27CawM8yF6fzr7WMlHCY9F/xD7lrn3GD5+PydHbrGLOCvt7bWfClO4C3OkHTC5QW5pKjHtXuV27ohFcosWG8WB/jwXmLam3cNsGmW27K0KHMBPJVY5rJbTo7j5zYMniMdyP55k+WjdPTbIF57C06smrGl7GvFXCyf+L2G9qZDTrxyHKuHiWo7zqndr5dAqnWBb1A1rsfrmxnsB7RAO2Am6TYsfbhWch68bkdbcxcsEyxKaxkGezyFveWf+etrdxCvClimiG+qoiIXp0scp6oz8gJYMx5kakmKIN1VzwFB2XwS6F+vZW+ju7X1gtyKuOni/1EAizzPMhwcwbzP6+Ie7MuBVpqJpDOqcTB1U5x6CNHSxXJD2i4TQxQMn66mc7vdMjyC5IYaRyjJ+ZnUR37uyfBkJ3Y3ZvlRNjgUeJASPr72k507GWJ5kGiUxBOM+Ll2LNxTs0YzmuYIjOVThrSW2KBgbSTbGh5dfnXVYQi7nrOBu3b7eVm0RciWTR15QIiNqlNf3miUpGQXQoJ7dBcCixmFpHyxhfw=
      on:
        tags: true
        repo: yoctore/yocto-hint