language: node_js
node_js:
- 6.11.1
- 6.11.2
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: bDB9J187sPMPq8sQ+9MOzdtCGx0RTz3+sKTQ4+dPeidnYeIxkeRaH8qEM/cTjbPj5mXU4FBsTQBMS6a/E3B2ZVlJmjcfeigfYisAzVf71SPhqX8sy7+ru7nV8HfnP6pNpoIvqapeoEii44KSDQAVxWNnwMcFMbb6TeHbzlNr2RCT9KXiovzX3Shob1bqtgwtTn/cXuTgLuvOx/poUtrVxGdWbuwj5FRwvPFEM0HTDVWjRDnhrG5mR+801U8BXr43ldZWwA70UoZUNHQHOk0CGqWpFGEZJ7Y+AZ7mRFfAfR74ICAQ7cxPQuuU5UMQGyP8iHVwPV35KoZiZVLlRnZ3udrWLVLTTmDAwYiwpiz9BoFwTJEWcEf0SnbntjB22M0EB8TcVBQpxFN5eIepDCjh15pFTdS7xLTULJC7Qj4pKC81XkuzFPK8xw0Xj9UrdM1M6LhElDAnRItVaw1DHOQ5FpmenYABRirknltlCOMmj4AA6UCf+UHJBd56BsMOMPL0VYGgOtNEuAgf4TcXzjaenDVZozyLj2GJL8S/XpJ0ZazwwJuAtTln9l5vua5XLKj7bR8BB0qrEL8RthwgvyNEOsFNp4pkpjJYvS5WNkS3ivf0cv4vN5jVNCLEFEJfJSIEPYfOTVV8mCLPBdPuDD2DoZ7MvCyEP6i93x5fMjCN73M=
  on:
    tags: true
    repo: yoctore/yocto-hint
before_install: npm install -g grunt-cli
install: npm install
