# http://eslint.org/docs/rules/
extends: [ "./yocto-node-es5-eslintrc.yaml" ]
env:
  node : true
  es6: true
rules:
  # ECMAScript 6
  arrow-body-style: [ 2, "as-needed" ]
  arrow-parens: [ 2, "as-needed" ]
  arrow-spacing: [ 2, { "before" : true, "after" : false }]
  constructor-super: 2
  generator-star-spacing: [ 2, { "before" : true, "after" : false }]
  no-class-assign: 0
  no-confusing-arrow: 2
  no-const-assign: 2
  no-dupe-class-members: 2
  no-duplicate-imports: 2
  no-new-symbol: 2
  no-restricted-imports: 0
  no-this-before-super: 2
  no-useless-computed-key: 2
  no-useless-constructor: 2
  no-useless-rename: 2
  no-var: 2
  object-shorthand: 0
  prefer-arrow-callback: 0
  prefer-const: 2
  prefer-destructuring: 0
  prefer-numeric-literals: 0
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 0
  require-yield: 2
  rest-spread-spacing: [ 2, "always" ]
  sort-imports: 0
  symbol-description: 0
  template-curly-spacing: 2
  yield-star-spacing: [ 2, "both" ]